# Generated by Django 5.2.7 on 2025-10-30 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True)),
                ('nid', models.CharField(blank=True, max_length=50, null=True, verbose_name='National ID')),
                ('designation', models.CharField(blank=True, help_text="Job title (e.g., 'Senior Software Engineer', 'Backend Developer')", max_length=100, null=True)),
                ('role', models.CharField(choices=[('HR', 'HR'), ('HR_MANAGER', 'HR Manager'), ('CHRO', 'CHRO'), ('MANAGER', 'Manager'), ('DEPARTMENT_HEAD', 'Department Head'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('CFO', 'CFO')], help_text='System role for permissions', max_length=20)),
                ('department', models.CharField(blank=True, help_text="Department name (e.g., 'IT', 'Sales', 'HR')", max_length=100, null=True)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Probation', 'Probation'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Temporary', 'Temporary')], max_length=50)),
                ('is_permanent', models.BooleanField(default=True)),
                ('employment_type_updated_from', models.DateField(blank=True, help_text='Date when employment type changed (e.g., Probation to Permanent)', null=True)),
                ('monthly_basic_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly basic salary for encashment calculation', max_digits=10)),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly gross salary including allowances', max_digits=10)),
                ('salary_per_day', models.DecimalField(decimal_places=2, default=0, help_text='Daily salary rate for leave encashment (auto-calculated or manual)', max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for hour-based calculations', max_digits=8)),
                ('is_in_notice_period', models.BooleanField(default=False, help_text='Is employee serving notice period?')),
                ('notice_period_start_date', models.DateField(blank=True, help_text='Date when notice period started', null=True)),
                ('notice_period_end_date', models.DateField(blank=True, help_text='Expected last working day', null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_introduced', models.BooleanField(default=False)),
                ('emergency_contact_info', models.TextField(blank=True, help_text='JSON or text with emergency contact details', null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_head', models.ForeignKey(blank=True, help_text='Department head (for approval chain)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_members', to='employees.employee')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATIONAL_CERTIFICATE', 'Educational Certificate'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('FITNESS_CERTIFICATE', 'Fitness Certificate'), ('OFFER_LETTER', 'Offer Letter'), ('RESIGNATION_LETTER', 'Resignation Letter'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_by', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant_id', 'email'], name='employees_e_tenant__f8556f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant_id', 'department'], name='employees_e_tenant__13bc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant_id', 'manager'], name='employees_e_tenant__075cac_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_type'], name='employees_e_employm_75cb00_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employees_e_is_acti_ff761b_idx'),
        ),
    ]
