# Generated by Django 5.2.7 on 2025-10-30 07:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('tenant_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Emergency', 'Emergency Leave'), ('Unpaid', 'Unpaid Leave')], max_length=50)),
                ('request_type', models.CharField(choices=[('leave', 'Leave Request'), ('encashment', 'Encashment Request')], default='leave', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('documentation_required', models.BooleanField(default=False)),
                ('required_doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('encashment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('encashment_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('policy_id', models.UUIDField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('current_approval_step', models.IntegerField(default=0)),
                ('approval_chain', models.JSONField(blank=True, default=list)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_by', models.UUIDField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['tenant_id', 'employee_id'], name='leaves_leav_tenant__0153ed_idx'), models.Index(fields=['status'], name='leaves_leav_status_fd17c7_idx'), models.Index(fields=['leave_type'], name='leaves_leav_leave_t_7fd2c9_idx'), models.Index(fields=['start_date', 'end_date'], name='leaves_leav_start_d_352125_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Emergency', 'Emergency Leave'), ('Unpaid', 'Unpaid Leave')], max_length=50)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('available', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_forward_expiry_date', models.DateField(blank=True, null=True)),
                ('encashed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year', models.IntegerField()),
                ('reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'leave_type'],
                'indexes': [models.Index(fields=['tenant_id', 'employee_id'], name='leaves_leav_tenant__ae7f51_idx'), models.Index(fields=['year'], name='leaves_leav_year_b8a23b_idx')],
                'unique_together': {('tenant_id', 'employee_id', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('commented_by', models.UUIDField()),
                ('commented_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commented_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_comments', to='leaves.leaveapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveCommentReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('replied_by', models.UUIDField()),
                ('replied_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('replied_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='leaves.leavecomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('approver_role', models.CharField(max_length=50)),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.leaveapplication')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('leave_application', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='LeaveAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performed_by', models.UUIDField()),
                ('performed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('performed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='leaves.leaveapplication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['leave_application', '-timestamp'], name='leaves_leav_leave_a_29ce83_idx')],
            },
        ),
    ]
